### ISSUE TITLE
[Bug Report] Connection — 1513b3a2-f9af-418e-9609-900cb7db8503

### ISSUE THREAD

**Issue by aboydnw** [developmentseed/cng-sandbox#458]
## Description

No description provided

## Context

- **Page:** /w/eedwio93/map/connection/1513b3a2-f9af-418e-9609-900cb7db8503
- **Connection ID:** 1513b3a2-f9af-418e-9609-900cb7db8503
- **Reported at:** 2026-05-13T16:04:36.222555+00:00

<details>
<summary>Console logs (2 entries)</summary>

```
[2026-05-13T16:04:22.314Z] ERROR: TypeError: this.props.onAfterRender is not a function
    at TU._drawLayers (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:1941:16225)
    at oG (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:2021:42653)
    at https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:2021:43824
    at Rc (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:91980)
    at rl (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:96462)
    at _l (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:105297)
    at rl (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:97021)
    at _l (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:105297)
    at rl (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:96449)
    at _l (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:105297)
[2026-05-13T16:04:29.447Z] ERROR: TypeError: this.props.onAfterRender is not a function
    at TU._drawLayers (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:1941:16225)
    at oG (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:2021:42653)
    at https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:2021:43824
    at Rc (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:91980)
    at rl (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:96462)
    at _l (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:105297)
    at rl (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:97021)
    at _l (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:105297)
    at rl (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:96449)
    at _l (https://storytelling.developmentseed.org/assets/index-B3Z4AYXr.js:9:105297)
```

</details>

**Comment by aboydnw** [comment]
## Triage Analysis

**Category:** bug — likely already fixed

**Affected area:** UnifiedMap / deck.gl rendering (connection map page)

**Summary:** The error `TypeError: this.props.onAfterRender is not a function` matches the regression fixed in PR #459 (commit `6749903`), which was merged ~10 minutes after this report was filed and shipped in release 2.3.3 (now on 2.4.0). The root cause was `UnifiedMap` forwarding an explicit `undefined` for `onAfterRender` to `<DeckGL>`, overriding deck.gl's internal noop default. The current code in `frontend/src/components/UnifiedMap.tsx` spreads the prop only when defined, and a regression test exists in `__tests__/UnifiedMap.test.tsx`.

**Suggested approach:** Confirm the connection page `/w/eedwio93/map/connection/1513b3a2-f9af-418e-9609-900cb7db8503` no longer reproduces the crash on production (current bundle should differ from `index-B3Z4AYXr.js`). If clean, close as fixed. If still reproducing, there may be a second, unrelated call site passing `undefined` — search for other DeckGL usages.

**Estimated scope:** 0 files if confirmed fixed; otherwise 1 file (the unguarded DeckGL caller).
